spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

gateway:
  ip: http://192.168.0.21/

order-service:
  url: http://order-service/order-service/%s/orders
