spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQBYrUby52QF1A0J/hEru0uOX/CmXVbZOiXOi6rKbrOdri83ITzM2ZLkbgfCAm6onhHHI2ldfkNaxT88RqViJgLuLA4WYFLxkShawZ5pS8WqLBd3ZDvqakH1hGv8JVW9SbgLRLYG4bvUkAnudnyavl2wXR4y2zvLVMmEWWgwiH3Ht3v64zSBN1/GSInYTTewi+ePHxhypRdVm9TiMabhW0u2Q8j2v124Kl+esDmy58tW5HOVCzYU+3VynZyVOm+VvXPwOvXrUtwGA2BMj2DNMCIN3YeJKzJIwixky2N4FE8fUg5KUaWDQaDyuwngeZjUAADrXOGbfqeGjUNYz8hfODG05rbZYhlYB3tAnwNbvy2vV4bOySlW5tpJ/zsruNQewfM='
    driver-class-name: org.h2.Driver

token:
  expiration_time: 3600000
  secret: '{cipher}AQBrck18Ps26wk0SDIuCMrxN9Az3sHsHM5vUqJssS28x/rF8l3v25ElDDNNWtOkDIyCKK0CY2FwCijUoozREeHNcSKL85O04urezC0JYk9Hj+JeG86XHE239keR2L6vefrFTFlIa526D3Hj0Q18pfQMaaFNNWeLb4ZIKzk5s8ng9o0bdeTbZRKGF9dNvbhbPSx2X4sramB/XcuPulcMFDTPLaVxSuIO6pZwvMzHZJYabWwKyy+lxGcRownRMaUqA+9crF+1hNj1cGDIWo7awj06WfPE4SfY8qzmu+ss6w0iT3V8PrIMnjyoR432h0yGXVyk4Tfx8R+ZAJhZ/v9Ge7KkusBH976Rt/VdW7VqPQ0opuu8rvn41Ts4h36gLW0uUS34lsqVBChp9Io2Do9ClM0EE'

gateway:
  ip: http://192.168.0.21/
